### ISSUE TITLE
Global Model Validation

### ISSUE THREAD

**Issue by jvantuyl** [schematics/schematics#210]
I've got some models that need to be validated at the model level based on criteria other than just the contents of some field.

As an example, I have an API that requires one (and only one) of a certain list of fields to have a value.  I'd imagine this is very common.  What I'd like to do is add a function, say validate_sane_request(), with the logic to check this.

Right now my only option is to define a check on one of the fields by name.  While this works, it's is a bit of a hack and the error message is counter-intuitive (i.e. errors come up on a field that isn't the one you omitted).

I think we should run any validators that don't validate a field afterwards as model validators.  I'm not positive how this meshes with partial handling (i.e. it makes sense that partial objects would not pass such sanity checks), but I'm pretty sure that edge-case isn't worth the much more common case of wanting a purely generic model validator.

If I were to code this, is there any interest in merging it?

**Comment by bintoro** [comment]
I'm currently wrapping up a validation refactoring/cleanup PR and would like to throw this feature in.

In addition to @jvantuyl's analysis above, here's something to consider: model-level validators are currently called even if the field's value is `None`. I'd like to stop doing this for two reasons:

  * Consistency with type-level validators, which are never called when the value is missing or `None`
  * Calling a validator with `None` means the same ought to happen with an undefined value too. In practice, this would mean supplying the raw `Undefined` object as the value. But that conflicts with the principle that applications should never have to deal with the `Undefined` placeholders unless they want to.

The only situation in which a validator needs to check for `None` is if it implements some kind of conditional `required` constraint. Typically such a constraint would depend on the values of several fields and would therefore belong in a global validator as proposed in this issue, not in a field-specific validator.

Since the global validator functions would receive the entire dataset as a dictionary argument, undefined values would pose no problem, as they would simply be absent.

**Comment by kstrauser** [comment]
Would it ever be the case that a user would expect a validator to cast None to a reasonable default, so that they'd want it to be run regardless?

**Comment by bintoro** [comment]
> Would it ever be the case that a user would expect a validator to cast None to a reasonable default, so that they'd want it to be run regardless? 

If we accept [this argument](https://github.com/schematics/schematics/pull/355#issuecomment-154555985), then that's not a *validator* concern.

I do think it would be useful to be able to perform all sorts of data mangling around import/export — PR #269 is an old draft of mine that deals with this. But since these operations can get much more elaborate than just providing a default value, tasking validators with all of it is not going to be feasible.

As for the specific use case of turning `None` into something else:

The undefined PR tentatively changes the behavior of field defaults so that the substitution is no longer triggered when `None` is provided (i.e., `None` is considered an explicit value). But I believe it would make sense to allow types to provide this option on a field-specific basis. For instance, I could imagine a `TimestampType` subclass that resets itself to the current time whenever the input is `None`. This sounds like a job for a dedicated hook, though — not a validator.

**Comment by jvantuyl** [comment]
This seems like a dead horse.  Not even sure if it applies anymore.  Closing.
