### ISSUE TITLE
Classes instead of instances in ModelType

### ISSUE THREAD

**Issue by jmsdnns** [schematics/schematics#341]
I don't like the way the current ModelType paradigm works.

The syntax for defining a `ModelType` is to list the _classes_ and not _instances_ of the class. This is less flexible.

In PR [#340](https://github.com/schematics/schematics/pull/340) I introduced a `PolyType` which will use a list of validators from type instances each with their own restraints, like `min_length` in the snippet below. Using classes, instead of instances, prevents this level of flexibility. I prefer to change the syntax for using `ModelTypes` than reduce functionality in the new `PolyType`.

From the snippet in PR 340:

```python
class Foo(Model):
    bla = ListType(PolyType([IntType(), StringType(min_length=3)]))
```

And the behavior of the `ModelType`:

```python
class Band(Model):
    name = StringType()

class Person(Model):
    band =  ModelType(Band) # this is the offending line
```

I would prefer `band = ModelType(Band())`

Another consideration is that default data would be possible for ModelTypes now too. I don't have a specific use case for this piece, but it is an interesting consequence of making the system internally consistent.

**Comment by bintoro** [comment]
I wouldn't really equate `PolyType` and `ModelType` in this way.

`PolyType` is special in that it is passed a further list of types. The arguments must be instances because that's how they get their properties.

All the other types, including `ModelType`, are "regular" types that define a concrete format for a field. Their arguments generally do not require instantiation: the class `Band` is a meaningful parameter to a `ModelType`, just like the integer `30` would be a meaningful parameter to `StringType(30)`. Instantiating the `Band` doesn't add any relevant information to it.

Default data would be passed as a `default` argument to the `ModelType`, not the `Band`. This is already possible today.

That said, it would be easy to modify `ModelType` so that it would accept both classes and their instances, but I don't readily see what this would accomplish.

**Comment by bintoro** [comment]
Looking at this again, I still stand by my earlier analysis that switching to instances isn't going to accomplish anything tangible, so I'm gonna close this for now, but please reopen as needed.
