### ISSUE TITLE
Allow serializing only imported fields with to_primitive and to_native

### ISSUE THREAD

**Issue by tuukkamustonen** [schematics/schematics#366]
As in the subject: allow something like:

    class Song(Model):
        ...
        class Options:
            serialize_only_dirty=True

Use case: I'm validating PATCH requests so wrapping the request payload into schematics model instance and would like to pass the instance deeper into code and serialize it later on when needed.

The problem is, my API allows clearing fields by setting them to `null`. So, by default all the (even non-required) fields are converted and thus cleared and I cannot use `serialize_when_none`, because then nulls wouldn't get through at all.

I could pass my request payload as is, yeah, but I'd rather pass schematics model and suffer the performance hit when needlessly serializing model into dict again...

**Comment by bintoro** [comment]
This is in the works.

As of now, Schematics offers no way to distinguish an explicit `None` from "not set" (or "missing"). This causes all kinds of headaches when dealing with partial data, as you've discovered.

I've wanted to fix this for a long time, but work on the feature was halted due to lack of feedback and other issues. But it's coming in the next few weeks.

Right now, I'm planning to deprecate `serialize_when_none` and replace it with a setting like `export_level`, which might look something like this:

  * 0: never export
  * 1: don't export when empty (`None`, `[]`, `{}`, undefined)
  * 2: don't export when `None` or undefined
  * 3: don't export when undefined
  * 4: always export

Levels 1 and 4 are what's currently being offered via `serialize_when_none`.

Also see #360, which deals with applying defaults to incoming data.

**Comment by tuukkamustonen** [comment]
That approach and those levels sound very reasonable, and would fulfill my needs.

I don't know schematics internals, but would it make sense to allow providing a custom serializer (per model or per field)? And then bundle implementation for the ones you listed.

Also #360 makes sense.

Should I close this ticket - you said it's in the words, is there another ticket somewhere?

**Comment by bintoro** [comment]
> I don't know schematics internals, but would it make sense to allow providing a custom serializer (per model or per field)? And then bundle implementation for the ones you listed.

Incidentally I'm working on this, too.

The serialization mechanism is already extensible up to a point, but it could be better. Specifically, I want to generalize the export system so that, instead of choosing between `to_native()` and `to_primitive()`, you could specify a mixed representation as well.

Consider:

```python
class Foo(object):
    def __init__(self, x, y):
        self.x, self.y = x, y

class FooType(BaseType):
    def to_native(self, value, context):
        # convert dict to Foo instance
    def to_primitive(self, value, context):
        # convert Foo instance to dict


class M(Model):

    _id = ObjectIdType()
    dt = UTCDateTimeType()
    foo = FooType()
```

Let's say I want to export an `M` instance and feed it to PyMongo. Well, PyMongo requires an actual `ObjectId` instance but wouldn't understand a native `Foo` instance. So ideally I'd like to export

  * the model container itself as primitive (`dict`)
  * `_id` as native (an `ObjectId` instance)
  * `dt` as native (a `datetime.datetime` instance)
  * `foo` as primitive (`dict`).

There's currently no simple way to accomplish this.

My current plan is to specify these things in an `ExportProfile` object, which could be extended by applications in any way they want. During serialization, the profile object is consulted about what to do with each field.

Right now, `export_loop` (responsible for serializing models) does take a `field_converter` function that can already be customized if you want to intercept a converted value and do something with it. But this mechanism has two shortcomings: it doesn't let you drop values altogether, and the `field_converter` is not invoked for compound types. I intend to fix the latter issue by unifying the interfaces so that the same `field_converter` can be applied to all fields. The first limitation is something the `ExportProfile` objects could eventually address.

> is there another ticket somewhere?

Well, the issue has been raised several times, and #249 is being kept open.

#263 is a RFC on the feature. See [this comment](https://github.com/schematics/schematics/issues/263#issuecomment-150047136) for a summary of the current alternatives for the internal implementation.

**Comment by bintoro** [comment]
This feature now exists on the development branch, see #372.
