### ISSUE TITLE
ListType(StringType) will validate 'foo'

### ISSUE THREAD

**Issue by jmsdnns** [schematics/schematics#376]
```python
>>> from schematics.types import StringType
>>> from schematics.types.compound import ListType
>>> l = ListType(StringType)
>>> l.validate('foo')
'foo'
```

d'oh!

**Comment by bintoro** [comment]
Yep, that's crazy, but it's by design. This happens because `ListType._force_list()` coerces everything:

```python
        ...
        except TypeError:
            return [value]
```
...although I wonder why the output would be `'foo'`. I get `['foo']` as expected.

Anyway, I don't think this is an appropriate default behavior at all. I've [mentioned before](https://github.com/schematics/schematics/pull/364#issuecomment-158752394) that I'd like to put this behind a switch.

**Comment by bintoro** [comment]
It turns out that in order for `flatten` and `expand` to work, `ListType` must accept dictionaries because there's no way for `expand` to disambiguate between a list and a dictionary. This may help explain why the coercion behavior of `ListType` is so lax.

A couple of options come to mind:

* Put loose behavior behind a `coerce=True` setting. Deal with `expand` by implementing a heuristic whereby a mapping whose keys match an uninterruptible sequence of natural numbers `[0, 1, ...]` is presumed to be a list.

* Preserve coercion rules for iterables but don't create a 1-element list to hold the value as a last resort, which is what this specific issue is about.

I think I'm going to go with the second option for the time being. If strict/loose options are going to be springing up all over the place, I'd like there to be a well-defined system for overriding them at import time as well.

**Comment by jmsdnns** [comment]
into it!
