### ISSUE TITLE
six missing from tests_require

### ISSUE THREAD

**Issue by foxx** [schematics/schematics#386]
Latest version of schematics (2.0.0-dev) is broken when using `setup.py test` from another project which requires `schematics` for its own tests.

```
  File "/home/vagrant/.pyenv/versions/2.7.11/lib/python2.7/site-packages/setuptools/sandbox.py", line 236, in runner
    _execfile(setup_script, ns)
  File "/home/vagrant/.pyenv/versions/2.7.11/lib/python2.7/site-packages/setuptools/sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-gk_nyu/schematics-2.0.0.dev1/setup.py", line 8, in <module>
    'six>=1.10',
  File "/tmp/easy_install-gk_nyu/schematics-2.0.0.dev1/schematics/__init__.py", line 7, in <module>
  File "/tmp/easy_install-gk_nyu/schematics-2.0.0.dev1/schematics/models.py", line 8, in <module>
ImportError: No module named six
```

It would appear that `six` is missing from `test-requirements.txt`

**Comment by bintoro** [comment]
Thanks for reporting this.

It's not the requirements file but a combination of several factors:
* `setup.py` does `import schematics` to retrieve the version number.
* `__init__.py` imports the entire library right away. (This is what has changed.)
* It's a source distribution.

There's no reason why Schematics should be a source distribution. It's just for historical reasons I guess. There's now a universal wheel on PyPI. Can you retry the build and let me know if the issue went away?

**Comment by foxx** [comment]
Sadly this seems to result in the following;

```
setup(tests_require=['schematics>=2.0.0'])
```

```
Searching for schematics>=2.0.0
Reading https://pypi.python.org/simple/schematics/
No local packages or download links found for schematics>=2.0.0
error: Could not find suitable distribution for Requirement.parse('schematics>=2.0.0')
```

According to docs, referencing packages inside `tests_require` for usage with `python setup.py` does not use wheel.

Not too sure where to go next on this, as I haven't worked much with wheels yet

**Comment by bintoro** [comment]
Can you explain to me the relevance of `tests_require` in today's world? I thought it was more or less obsolete. For example the testing dependencies for Schematics would be installed by `pip install -r test-requirements.txt`.

The fact that `tests_require` is satisfied through `easy_install` is problematic not only because it doesn't understand wheels. It also doesn't understand the difference between a stable and a development release.

**Comment by foxx** [comment]
Sure, so I'm using `pytest` which is triggered via `python setup.py test`. This looks at `setup.py` to determine which packages are required for testing, and then installs them into an adjacent `.eggs` folder, or into the project root itself (depending on whether you're using py2/py3). This allows you to run a project test suite without having to install its dependancies globally, and is considered standard practice afaik. 

Are you aware of any better approaches? I've double checked the docs for pytest and setuptools, but found nothing to suggest otherwise.

**Comment by bintoro** [comment]
How about [tox](https://tox.readthedocs.org/en/latest/)?

All you need is a `tox.ini` file that can be as simple as:

```
[tox]
envlist = py27, py33, py34, py35

[testenv]
commands = py.test
deps =
    pytest
    lib1
    lib2
    ...
```

Then just run `tox`. It creates virtualenvs and keeps them there to avoid reinstalling unchanged dependencies all the time. It's very configurable and has direct support from pytest to include pytest directives in `tox.ini`.

**Comment by foxx** [comment]
Tox is certainly an alternative option, but it's arguable that both approaches should be supported given that `tests_require` is still a valid and widely used approach. Other source distribution projects work fine with this approach too, is there any particular reason why schematics can't do the same?

**Comment by foxx** [comment]
Also, I can see that `__version__` is read from `schematics` inside `setup.py`, triggering an import on `models.Model` which is what's causing this conflict from what I can tell. 

Other projects such as Django get around this by not importing this stuff inside [`__init__`][1]. That way you could still store `__version__`, without breaking `setup.py` usage. From what I can tell, all that would need to change is to remove `from .models import Model` from `__init__.py`

[1]: https://github.com/django/django/blob/master/django/__init__.py

**Comment by bintoro** [comment]
Your diagnosis is quite correct. I thought I explained this in my [first reply](https://github.com/schematics/schematics/issues/386#issuecomment-179975912).

The import is there for a reason: to ensure modules are imported in a predefined order. This, in turn, is to ensure that patches don't inadvertently introduce circular dependencies that only crop up when a particular module is imported first.

> `tests_require` is still a valid and widely used approach

Can you point to any evidence of this?

I looked at a few major projects (Django, SQLAlchemy, Flask), and, of those, only SQLAlchemy still includes `tests_require` in addition to its tox config. And it has to resort to [this kind of mess](https://github.com/zzzeek/sqlalchemy/blob/master/setup.py#L110) to extract the version number.

`tests_require` is also not mentioned *at all* in the [Python Packaging User Guide](http://python-packaging-user-guide.readthedocs.org/en/latest/), which is the most current resource.

That said, I'll probably solve this one way or the other before 2.0.0 is out. Have you by any chance noticed that 2.0.0.dev1 is a *development* release? This illustrates why relying on obsolete tools is a problem — your test script shouldn't even be trying to install it by default because it's a pre-release.

**Comment by foxx** [comment]
> your test script shouldn't even be trying to install it by default because it's a pre-release

> README: It is recommended that new users get started with the latest development release instead of the stable release. To do this, add the --pre option when installing via pip:

It was actually using `1.1` by default, however I forced it to `2.0.0` as per instructions from README seen above.

> Can you point to any evidence of this?

Django would be the other example, seen [here][1]. There's nothing in the [setuptools][3] docs to suggest that these attributes have been deprecated. 

> tests_require is also not mentioned at all in the Python Packaging User Guide

Nor is `dependency_links`, yet that also has valid use cases. 

If you look at the pypa [roadmap][4], you'll see that `test_requires` is included.


[1]: https://github.com/django/django/blob/master/setup.py#L32
[2]: http://tox.readthedocs.org/en/latest/example/pytest.html
[3]: https://pythonhosted.org/setuptools/setuptools.html
[4]: http://pypaio.readthedocs.org/en/latest/roadmap/

**Comment by bintoro** [comment]
The issue is not with `test_requires` per se; indeed there are plans to make it part of the package metadata specification so that `pip` could also access that information. Then, libraries could go back to declaring their test dependencies inside `setup.py` if they like. This is what the PyPA roadmap means.

The issue is with **setuptools**, as it continues to use the ancient `easy_install` to deal with dependencies. In other words, it's `setup.py install` and `setup.py test` that are obsolete. The irrelevance of `tests_require` is just an artifact of this, since no one besides setuptools can access that data currently.

> It was actually using 1.1 by default, however I forced it to 2.0.0 as per instructions from README seen above.

The README also instructs to use `pip`. It has been the recommended way to install packages for years now. Please read http://stackoverflow.com/questions/3220404/why-use-pip-over-easy-install.

> Django would be the other example, seen here.

Seen where? There is no `tests_require` or `test_requires` to be found anywhere in that file.

FWIW, this whole debate is somewhat moot, as the `six` dependency is likely to go away in the next release. But should another dependency arise in the future, we're certainly not going to start jumping through hoops to accommodate practices that are outdated and generally discouraged.

**Comment by wiggin15** [comment]
> In other words, it's setup.py install and setup.py test that are obsolete

Can you point out to any evidence of this? You sound pretty adamant about this but I'm not sure it's true.

* wheels can't replace source distributions and "setup.py install" entirely. In case of packages with binary extensions (i.e. not universal wheels), a package author can't upload a wheel distribution for all possible platforms Python is supported on (not to mention that for "linux", wheels don't differentiate between different linux distros and that can be a problem). This is why source distributions are still required. sdists (installed with setup.py install) are here to stay, alongside wheels.
* easy_install is still actively maintained and widely used. Maybe everyone should switch to pip, but not everyone has.
* It's not just easy_install that uses sdists and 'setup.py install' for installation. There's also buildout, conda (when building packages), pytest (as seen in this ticket), and probably many more tools that cropped up over the years.

The packages you mentioned: Django, Flask, SQLAlchemy, even pip and setuptools all have source distributions. I would like to ask that you please don't drop sdists, otherwise we will not be able to use schemtics (we use buildout).

**Comment by bintoro** [comment]
@wiggin15 Source distributions are not going anywhere. I have only removed the sdist of the current developmental release because it fails to build when invoked without `six` present (and because I have no idea how `easy_install` treats pre-releases currently).

pytest certainly does not depend on sdists or `easy_install` in any way. I'm curious if there are any important projects around that still advise `setup.py test` as the preferred way of running their test suite.

Anyway, likely the simplest solution is just to maintain the version number in two files so as to avoid importing the whole library during `setup.py`. Or does anyone have any bright ideas?

* The version number should be hardcoded in the source.
* Parsing `__init__.py` by hand is just... ugly.
* I want to make sure patches don't introduce circular dependencies that may not be apparent at first. (Schematics has a history of this.) So that's why I'm now importing `models.py` in `__init__.py`.

**Comment by bintoro** [comment]
`setup.py` no longer imports the library in v2.0.0.dev2, which  is now on PyPI.

**Comment by foxx** [comment]
Nice, thank you @bintoro
