### ISSUE TITLE
Invalid handling of py2 str in StringType

### ISSUE THREAD

**Issue by charlax** [schematics/schematics#395]
For some reason, I'm getting:

```
ConversionError("Couldn't interpret 'hello' as string.")
```

I did a bit of investigation, and saw that in `compat.py`, `str` maps to `unicode`, and `bytes` maps to `str` (I'm using py2). This made my debugging a lot more confusing than necessary, because I was wondering why I was getting `isinstance('hello', str) == False`.

Then, looking at how `StringType` works:

```python
    def to_native(self, value, context=None):
        if isinstance(value, str):
            return value
        if isinstance(value, self.allow_casts):
            if isinstance(value, bytes):
                try:
                    return str(value, 'utf-8')
                except UnicodeError:
                    raise ConversionError(self.messages['decode'].format(value))
            else:
                return str(value)
        raise ConversionError(self.messages['convert'].format(value))
```

This was going straight to the last line, because `self.allow_casts == (<type 'int'>, <type 'unicode'>)`, and `bytes == <type 'unicode'>`. I'm pretty confused as to why that's the case and still debugging why. In any case, I think the way the `six` packages does it is much easier to understand and debug.

**Comment by charlax** [comment]
It looks like `bytes` is correctly set to `str` at the end of compat file (I checked this at runtime). Same at the end of `transforms.py`. 

But when `types/base.py` is loaded, `bytes` is `unicode`.

**Comment by charlax** [comment]
This was caused by an invalid rebase on my part.

**Comment by bintoro** [comment]
The compatibility features (builtin reassignments in particular) should under no circumstances leak outside the Schematics library. They used to, but #391 fixed this so that `... import *` no longer screws up globals on the importing side.

Under Python 2, I get:

```python
>>> from schematics.types import *
>>> type(StringType().convert('foo')) # should return 'unicode' on Py2 and 'str' on Py3
<type 'unicode'>
```

Anything else should be considered a bug.

I'm a firm proponent of using standard Python identifiers instead of some `six.text_type` nonsense. Once that stuff is sprinkled all over a codebase, it's likely to remain there forever.
