### ISSUE TITLE
to_native returns Model instance in v2.0.0-dev2

### ISSUE THREAD

**Issue by rskumar** [schematics/schematics#405]
`to_native` in 1.x version seems to return dict with native python values, while in 2.x-dev[1,2] its returning model object. Is that intentional change? What is recommended way now to get dict with native values?

Example:
```
class Product(Model):
    name = StringType(required=True, min_length=3, max_length=100)
    ...
    updated = DateTimeType(required=True)

# Usage
product = Product(kwargs)
print(type(product.to_native()))

>> <class 'proto.models.Product'>
```

**Comment by bintoro** [comment]
Yes, this is intentional. Native means the full representation, so it seemed illogical that `Model.to_native` should convert models to dicts, as a dictionary is the *primitive* representation of a model.

Essentially, in 1.x `to_native` outputs a hybrid format where models are converted to dicts but scalar values remain native. In 2.0, the same output is produced by `to_dict`. Does this make sense?

**Comment by rskumar** [comment]
I understood it partially. `to_dict`  would suffice and more common for scenario in other libs too, as well as the name `to_dict` says all what it will do. I will migrate my code using `to_native` to `to_dict`.

I guess, `to_native` in 2.x will just convert the supplied data types to defined schema type's native type. Let me play and understand it more. :)

**Comment by bintoro** [comment]
Actually, I'm having second thoughts about this change.

#368 removed `to_native()` from compound types, so today it would be reasonable to think of "native" and "primitive" as meaningful for atomic types only (i.e., not implying anything about whether the container is a model or a dict).

Now if you look at it that way, then it makes perfect sense for `Model.to_native()` to produce a dictionary populated with native scalars. So, I might be up for sticking with the v1 semantics after all.

Does anyone else want to chime in here?

**Comment by lkraider** [comment]
`to_native` means you can get your custom class instances (for intermediary work), while `to_primitive` will only give _pure_ serializable types (for output).

**Comment by bintoro** [comment]
@lkraider Yeah, that's what it means now (in v2 dev), but in v1 `Model.to_native()` produced a dictionary structure, with only the atomic values as native. And I'm pondering whether to go back to that.

The new `to_native` is essentially just the old `to_native` followed by import into a new instance.

**Comment by bintoro** [comment]
Just to be clear, I'm talking about what happens when you call `someinstance.to_native()`, where `someinstance` is already a model instance.

**Comment by lkraider** [comment]
That what it means in v1 too. The idea in v1 is that a dict of native fields == a Model instance, so they are interchangeable.

We would unpack the Models so that passing the native fields around for further processing would not trip or depend upon the Model API.

What is the rationale for keeping the Model instances?

**Comment by bintoro** [comment]
I think we're talking past each other a bit here. In v1, `instance.to_native()` produces a dictionary of native scalars. In v2.dev it produces a model instance that has been put through the export machinery; this is to apply roles or whatever there might be.

In v2.dev, `instance.to_dict()` is the equivalent of the old `instance.to_native()`.

The reasoning had its origins in the old codebase where `to_native` would appear in `ModelType` & co, where it would handle data import. In other words, the *native form of a model* was strongly implied to be a Model instance, not a dictionary. It looked like a bug that `to_native()` would produce an instance in one code path but a dictionary in another.

But #368 addressed the conceptual issue by introducing the import/export methods, which are properly orthogonal to native/primitive concerns. So now I think returning a dictionary from `instance.to_native()` does make sense, as it's an export operation. Thus, I'm considering going back to the old behavior and getting rid of `to_dict()`.

**Comment by lkraider** [comment]
Yeah, I think I agree with your last consideration. This would also affect the sub-models, correct?

**Comment by bintoro** [comment]
> This would also affect the sub-models, correct?

Yea, submodel representation should be in sync with the root container, if that's what you mean.

In fact, I just fixed a long-standing bug related to this. It turned out that, in v1, if you used the functional API to import a hierarchical model, the submodels would still be imported into `Model` instances. Only the root level was returned as a dictionary.

I think it's pretty clear that submodels should only be instantiated if the process was initiated from a `Model` method or constructor.

Ref: 4fa0087.
