### ISSUE TITLE
PolyModelType doesn't provide _mock method

### ISSUE THREAD

**Issue by omgq** [schematics/schematics#416]
I found PolyModelType fields would cause get_mock_object() raising exception since it doesn't implement _mock method.

**Comment by bintoro** [comment]
`BaseType` provides a fallback `_mock()` implementation. What exception are you getting?

**Comment by omgq** [comment]
Oh, I see. Thanks.

It's the default implementation of returning None causing exception in my app code.

Any plan to implement a random-pick mocking mechanism like ListType?

**Comment by bintoro** [comment]
The current plan is actually to deprecate/remove `PolyModelType` in v2.0. If it's not removed right away, a simple `_mock()` could be added.

Barring unforeseen difficulties, the standard `ModelType` will get a subclass detection ability that is an improved version of what `PolyModelType` has now. Supporting unrelated classes in the same field likely becomes a matter of `UnionType` composition.

**Comment by omgq** [comment]
@bintoro Thanks for your explanation. 

BTW, may I ask how to model following structures in some elegant way with Schematics:
```Javascript
{
	"type": "a",
-->	"a": {
		...
	}
}
{
	"type": "b",
--> "b": {
    	...
    }
}
```

Notice that the field name has a dependency with the value of type field.

**Comment by bintoro** [comment]
@omgq The best way depends on the details of the situation, which are kind of lacking in your example.

One obvious method is to create distinct models via composition. If there are other accompanying fields that are specific to the `'a'` or `'b'` variant, this approach probably makes the most sense.

```python
class Container(Model):
    type = StringType()
    # Other common fields go here.

    def __new__(cls, raw_data={}, *args, **kwargs):
        submodel = raw_data.get('type')
        class_ = {'a': AContainer, 'b': BContainer}.get(submodel, cls)
        return super(Container, cls).__new__(class_, raw_data, *args, **kwargs)


class AMixin(Model):
    a = ModelType(A)
    # Other 'a'-specific fields go here.


class AContainer(Container, AMixin):
    pass

...
```

```python
>>> Container({'type': 'a'})
<AContainer instance>
>>> Container({'type': 'b'})
<BContainer instance>
>>> Container()
<Container instance>
```

There are ways to handle this within a single model as well.

Since `UnionType` doesn't yet support multiple `ModelType` variants, you'll have to do something like this:

```python
class M(Model):
    submodel = PolyModelType([A, B, C], deserialize_from=['a', 'b', 'c'])
```

That's assuming `PolyModelType` is able to identify the correct class from the data alone (the substructure keyed by `'a'` or `'b'` in your example).

If this isn't enough (e.g., you need two-way operation or the data is ambiguous), then it's possible to extend the import machinery and modify the input data before it's operated on (and similarly for outgoing data).

Unfortunately, how exactly to do this is in a bit of a flux right now. I'm working on refactoring the `Model` API as we speak. Something that you can safely do right now is override `Model.__init__` (for incoming data) and `Model.(to_native|to_primitive)` (for outgoing data).

In `__init__`, you could insert a `type` field in the raw data that allows `PolyModelType` to identify the model. Of course, you could also do this in the surrounding code before the source data is even passed to the model constructor.

In the future, you could set something like `app_data={'submodel': B}`, and then use `UnionType` with a custom resolver function like so:

```python
class MultiModelType(UnionType):

    types = (ModelType(A), ModelType(B))

    _type_mapping = {
        A: types[0]
        B: types[1]
    }

    def resolve(self, value, context):
        return self._type_mapping[context.app_data['submodel']]
```

Note that this is just a sketch; I'll have to think on it.

**Comment by omgq** [comment]
@bintoro Excellent explanation. Thanks for your detailed description.

Personally I prefer much the "composition" method.

Since it seems something like field resolving order problem, is it possible to introduce ordering on dependency between fields into Schematics? So that when doing exporting or importing, fields could be serialized/deserialized according to their dependency of other fields. 

However, it's certainly an exceptional case for normal modeling, maybe my idea of field dependency would cause too much complexity.

Thanks anyway.

**Comment by bintoro** [comment]
> Since it seems something like field resolving order problem, is it possible to introduce ordering on dependency between fields into Schematics?

Manipulating data on import/export depending on what fields are present is already possible today. I'm just not really sure what it is you're trying to do here:

* Do you want the final model to have a field called `a` if the data had `"type": "a"`?

* Or do you want the final model to have a single field, let's say `submodel`, to hold the nested structure, regardless of what the type was?

**In the first case** there's nothing to stop you from defining one model that can accommodate several possibilities:

```python
class M(Model):
    type = StringType()
    a = ModelType(A)
    b = ModelType(B)
```

```python
>>> m = M({'type': 'a', 'a': {}})
>>> m.a
<A instance>
>>> m = M({'type': 'b', 'b': {}})
>>> m.b
<B instance>
```

The unused field will contain `None`. To prevent it from being exported, you can set `export_level=NOT_NONE` on the `ModelType` fields.

**In the second case** you would either use `PolyModelType` or the composition approach:

```python
class AMixin(Model):
    submodel = ModelType(A, serialized_name='a')

class AContainer(Container, AMixin):
    pass

class BMixin(Model):
    submodel = ModelType(B, serialized_name='b')

class BContainer(Container, BMixin):
    pass
```

This will cause `"a"` or `"b"` to be used both for import and export, but the model instance will only contain a field called `submodel`.

```python
>>> c = Container({'type': 'a', 'a': {}})
>>> c
<AContainer instance>
>>> c.submodel
<A instance>
>>> c.to_primitive()
{'type': 'a', 'a': {...}}  # `submodel` exported as `a`
```

**Comment by omgq** [comment]
@bintoro  Thanks for your patience answering my question. Great experience for me to learn detail about Schematics.

Sorry for my previous question, which I didn't explain it with enough description.

I'm working on some project related to some web service API, which has payload of JSON format and includes some format as I described before(dynamic field name related to another "type" field value).

The project doesn't use Python language, but I figured out some idea since I found Schematics might help me a lot:
1. Use Schematics to describe the whole service protocol
2. Enumerate the models writing in Schematics and Translate them into target-language codes(might involve some IL code-emitting technique to speed up runtime efficiency)


So, the more detail and logic Schematics could help to describe, the less tricks would involve to translate, and even I'm thinking about multiple-language targetting in the near future. 

However, in spite of the methods(composition, submodel, and UnionType) you provided which are so great, I thought they might not be the most direct method to describe the detail and logic of field relationships.

The model in my imagination might seem something like following:
```python
def claim_func(field, data):
	metadata = field.metadata
	return metadata["poly_mapping"][data[metadata["field_depend"]]]
class OneModel(Model):
    type=StringField()
    payload=PolyModelType([A, B], 
                          deserialize_from=itemgetter('type'),
                          serialized_name=attrgetter('type'),
                          claim_function=claim_func,
                          required=True,
                          metadata={"field_depend": "type",
                          			"poly_mapping": {"a": A, "b": B}
                          			}
                          )
```

The code above won't work due to the params of deserialze_from and serialize_name support string type only currently. And maybe callable type isn't the most suitable type to describe field dependency(since some meta info requires to be recorded or there'll be touble in translating phase), I'm just illustrating some idea.

**Comment by bintoro** [comment]
It seems to me you want to have a completely dynamic schema. While Schematics is pretty flexible, the trouble is that there are literally infinite ways in which a schema could be dynamic. Therefore, the canonical way to deal with these cases is by pre-processing the payload a bit so that it conforms to at least some basic constraints.

The example code you posted is almost workable. There are only two things missing:
* Make sure that `PolyModelType` can see the `type` member, which in your case lives *outside* the actual data that is passed to the field.
* Rename the key indicated by the `type` member to `"payload"` before import conversion.

```python
def __init__(self, data, *args, **kwargs):
    type = data['type']
    data['payload'] = data.pop(type) or {}
    data['payload']['type'] = type
    super().__init__(data, *args, **kwargs)
```

Add that to the model and take out the spurious `itemgetter` stuff, and it'll work.
