### ISSUE TITLE
StringType w/ choices does not convert field

### ISSUE THREAD

**Issue by riccardomurri** [schematics/schematics#456]
I am trying to use `schematics` to validate a simple dict structure and convert
it back to Python `dict`; one of the fields is of type "string" and the value
must be drawn from a set of choices.

Please have a look at the following session::

```
In [61]: from schematics.models import Model

In [62]: from schematics.types import StringType

In [63]: class MyModel(Model):
   ....:     provider = StringType(required=True, choices=['a','b','c'])
   ....:

In [64]: m = MyModel()

In [65]: m.convert({'provider':'a'})
Out[65]: {'provider': u'a'}

In [66]: m.to_dict()
Out[66]: {'provider': None}
```

Why is the `'provider'` field in the final converted dictionary set to `None`?

**Comment by riccardomurri** [comment]
BTW I'm using `schematics==2.0.0.dev2` installed from PyPI.

**Comment by x** [comment]
I might be wrong, but I think this is a misunderstanding of what the `convert` method does. It exists to convert an unvalidated dict into the right types. For example...

```python
In [1]: from schematics.models import Model

In [2]: from schematics.types import IntType

In [3]: class Foo(Model):
   ...:     bar = IntType()
   ...:

In [5]: foo = Foo()

In [6]: foo.convert({"bar": "10"})
Out[6]: {'bar': 10}
```

I think the issue here is that you're trying to use `m.convert` to add the values of the dict to `m`.  You can do this by just passing it into the constructor.
```python
In [3]: class MyModel(Model):
   ...:     provider = StringType(required=True, choices=['a','b','c'])
   ...:

In [4]: m = MyModel({'provider': 'a'})

In [5]: m.to_dict()
Out[5]: {'provider': u'a'}
```

This will, at the very least, catch things like rogue fields in the dict you pass to the constructor. If you wanted to run the actual field validators (e.g. `choices`), you have to explicitly call the `validate` on `m` before `to_dict` to raise the exception.

```python
In [4]: m = MyModel({'provider': 'a'})

In [5]: m.validate()

In [6]: m.to_dict()
Out[6]: {'provider': u'a'}
```

**Comment by bintoro** [comment]
The explanation given by @x is correct. There's also the `import_data` method for merging more data into an existing instance.

**Comment by riccardomurri** [comment]
Thanks for the explanations!
