### ISSUE TITLE
Unmaintained

### ISSUE THREAD

**Issue by rmb938** [schematics/schematics#465]
Is it safe to assume this project is no longer maintained? Considering there has been very little activity since May of early this year. 

@bintoro @jmsdnns @kracekumar If you guys need more people to help out I am more than happy to lend a hand.

I use schematics in a lot of my projects since there are not any other libraries that have similar features. I would like to continue using it but I am currently forced to make bug fixes and add features on my own forks.

**Comment by bintoro** [comment]
The situation sucks, but please do not despair. I've been swamped with actual income-generating work, but I fully intend to get back to Schematics with a vengeance.

@rmb938, would you like to submit issues/PRs for some of the bugs you speak of?

**Comment by rmb938** [comment]
Well most of these already have prs open including my own; #449, #447, #436. As well as some sort of fix/improvement for #445

**Comment by lkraider** [comment]
I am working in schematics in my own fork to fix the SQLAlchemy integration (and more), it is getting ready to merge here.

I guess I could also work directly in this repo so it doesn't look dead...

**Comment by tuukkamustonen** [comment]
Overall, I don't think that it's optimal situation that we have (at least) 3 competing validation/serialization frameworks out there: `schematics`, `marshmallow` and `voluptuous`. Yeah, each of them has a slightly different focus, but as a silly customer I would love to see the power of all in just one package.

At the moment I'm using marshmallow for parameter validation (for it has built-in integration via `webargs`), voluptuous in tests (doing some asserts with it because it has the least-boilerplate syntax) and schematics for remaining code (compared to marshmallow, I access the data via `Model` instance, no need for custom construction). I think first schematics, then discovered voluptuous and then marhsmallow/webargs, which left me using different libraries for different tasks... yeah, one could say that's the way to go ("use the right tool for the task") but I don't quite agree.

If we had one strong/powerful/flexible package that would get the love of all the authors, that would rock. There's lots of duplication over the projects. But, I know I'm whining here, just wanted to speak out my dreams :)

**Comment by harlowja** [comment]
Agreed, all seem to do similar stuff; each a little bit differently.

**Comment by kracekumar** [comment]
@rmb938 Glad that you brought this up. In my opinion, schematics is stable and has required API's to work for most of the cases.

I haven't been contributing to the project since there isn't any active development other than @bintoro's work. He knows what he is doing.At my last job, I used `schematics` as validation library for Flask API. So feel free to get involved. I am all up for new contributors who can make schematics better.

I feel the more work lies in `documentation` and building adapters on top of schematics for `Django, Flask` or any other library which needs a validator.

**Comment by toumorokoshi** [comment]
Hi,

if this is stable, can we see an official release of the 2.0 version?

I've had to add in a bunch of 2.0.0a1> version specifiers for my projects, because I'm starting fresh and want to use the most forwards-compatible choice.

**Comment by danqing** [comment]
Would love to see some of the PRs being merged. @bintoro any blockers on the PRs proposed by @rmb938 et al.?

**Comment by lkraider** [comment]
I've addressed some of the PRs. I would like to have #369 / #445 in v2.0 as well.

**Comment by toumorokoshi** [comment]
@lkraider are you looking for volunteers on those? I get the general goal of sticking all data in errors: I could sketch my proposal and take a stab if that'll help unblock 2.0.

**Comment by lkraider** [comment]
Sure, I would gladly review a PR on that!

**Comment by lkraider** [comment]
2.0.0 on PyPI:
https://pypi.python.org/pypi/schematics/2.0.0

**Comment by douglas-treadwell** [comment]
@tuukkamustonen, @harlowja and others on this thread, you might be interested to look at [Marshmallow Models](https://github.com/douglas-treadwell/marshmallow-models).
