### ISSUE TITLE
Why is the _append_field() method private?

### ISSUE THREAD

**Issue by raffclar** [schematics/schematics#575]
I use _append_field() to avoid having to write duplicate code and reduce the risk of bugs. Cheers for adding it!

I just want to know why it's got the private convention?
I'm happy to make a PR if it turns out it could be made public.

**Comment by lkraider** [comment]
Mainly because of this TODO:
https://github.com/schematics/schematics/blob/3a144be0aa50f68a4da917e8d957b924dedf9a52/schematics/schema.py#L30

The idea was to remove this dependence of the schema on the model.
This initializing of the field by passing in the model is basically used for the compound types to dynamically resolve string model refs.

The PR here would be to try and separate these functions:
- [ ] model depends on schema, but not the other way (break the double ref)
- [ ] field depend on schema instead of model (to keep the dynamic `options` access)
- [ ] compound types string model name resolver be refactored into some helper infrastructure code

**Comment by raffclar** [comment]
Thanks for explaining and for updating Schematics
